services:
  jaeger:
    image: cr.jaegertracing.io/jaegertracing/jaeger:2.12.0
    ports:
      - "16686:16686" # Jaeger UI
      - "4318:4318"   # OTLP HTTP receiver
      - "4317:4317"   # OTLP gRPC receiver
      - "5778:5778"   # Agent serve frontend
      - "9411:9411"   # Zipkin collector compatibility
    restart: unless-stopped
    environment:
      - SPAN_STORAGE_TYPE=memory
